version: '3'

services:
  trainer:
    build: .
    volumes:
      - ./mlruns:/app/mlruns
    command: python src/train.py --n_estimators 100 --max_depth 5

  server:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - ./mlruns:/app/mlruns
    command: python src/serve.py
    depends_on:
      - trainer